include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # Unused imports are errors
    unused_import: error
    # Unused locals are warnings
    unused_local_variable: warning
  exclude:
    # build_runner generated files
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Rules that conflict with the project conventions
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    sort_pub_dependencies: false
